export const SAGA_ACTIONS={
    HOME_CONTENT:'HOME_CONTENT/SAGA',
    LOGIN:'LOGIN/SAGA',
    GET_ME:'GET_ME/SAGA',
    SIGN_UP:'SIGN_UP/SAGA',
    UPDATE_USER:'UPDATE_USER/SAGA',
    UPDATE_USER_PASSWORD:'UPDATE_USER_PASSWORD/SAGA',
    FORGOT_PASSWORD:'FORGOT_PASSWORD/SAGA',
    RESET_PASSWORD:'RESET_PASSWORD/SAGA',
};

export const ACTIONS={
    LOADER:{
        BACKDROP_VISIBLE:'BACKDROP_VISIBLE',
        HIDE_BACKDROP:'HIDE_BACKDROP',
    },
    LAYOUT:{
        SHOW_HEADER:'SHOW_HEADER',
        HIDE_HEADER:'HIDE_HEADER'
    },
    HOME_PAGE_CONTENT:'HOME_PAGE_CONTENT',
    LOGIN:'LOGIN',
    LOGOUT:'LOGOUT',
    GET_ME:'GET_ME',
    UPDATE_ME:'UPDATE_ME',
    // cart actions start
    GET_CART_ITEMS:'GET_CART_ITEMS',
    INCREMENT_CART_QUANTITY:'INCREMENT_CART_QUANTITY',
    DECREMENT_CART_QUANTITY:'DECREMENT_CART_QUANTITY',
    DELETE_SINGLE_CART_ITEM:'DELETE_SINGLE_CART_ITEM'
};