export const SAGA_ACTIONS={
    HOME_CONTENT:'HOME_CONTENT/SAGA',
    LOGIN:'LOGIN/SAGA'
};

export const ACTIONS={
    HOME_PAGE_CONTENT:'HOME_PAGE_CONTENT',
    LOGIN:'LOGIN',
    // cart actions start
    GET_CART_ITEMS:'GET_CART_ITEMS',
    INCREMENT_CART_QUANTITY:'INCREMENT_CART_QUANTITY',
    DECREMENT_CART_QUANTITY:'DECREMENT_CART_QUANTITY',
    DELETE_SINGLE_CART_ITEM:'DELETE_SINGLE_CART_ITEM'
};